exception in epoch1
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 274, in <module>
    outImage = net(image)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 79, in forward
    L5 = self.c5(self.d4(L4))
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 23, in forward
    return self.layer(x)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\dropout.py", line 100, in forward
    return F.dropout2d(input, self.p, self.training, self.inplace)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\functional.py", line 1202, in dropout2d
    return _VF.feature_dropout_(input, p, training) if inplace else _VF.feature_dropout(input, p, training)
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 4.42 GiB already allocated; 0 bytes free; 4.47 GiB reserved in total by PyTorch)

exception in epoch39
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 266, in <module>
    for i, (image, mask) in enumerate(trainLoader):
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\utils\data\dataset.py", line 311, in __getitem__
    return self.dataset[self.indices[idx]]
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\data.py", line 42, in __getitem__
    mask = gray2Binary(mask)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\utils.py", line 40, in gray2Binary
    if img[i, j] > 0:
KeyboardInterrupt

